### ISSUE TITLE
[13.0] dms.file tree order

### ISSUE THREAD

**Issue by rbellanova** [OCA/dms#105]
Hi dear, I have found that sorting of columns in the file tree view does not work

![Peek 22-06-2021 11-47](https://user-images.githubusercontent.com/42999048/122903350-9cb64480-d34f-11eb-9157-3705b725a5f5.gif)

**Comment by rbellanova** [comment]
If it could be useful... problably the problem is on "_search" function

**Comment by rbellanova** [comment]
I solved in this way, removing the set operations in favor of recordset operations
Hope it could be useful

`
        file_ids = self.browse(result)
        directories = self._get_directories_from_database(result)
        for directory in directories - directories._filter_access("read"):
            file_ids -= directory.sudo().mapped("file_ids").ids
        return len(file_ids) if count else file_ids.ids`

**Comment by victoralmau** [comment]
> I solved in this way, removing the set operations in favor of recordset operations
> Hope it could be useful
> 
> ` file_ids = self.browse(result) directories = self._get_directories_from_database(result) for directory in directories - directories._filter_access("read"): file_ids -= directory.sudo().mapped("file_ids").ids return len(file_ids) if count else file_ids.ids`

Thanks, i have opened some change (https://github.com/OCA/dms/pull/106) to solve it.

**Comment by victoralmau** [comment]
Hi, it's solved on 13.0 and 14.0
