### ISSUE TITLE
Mobile VIew

### ISSUE THREAD

**Issue by gdgellatly** [OCA/dms#11]
Hi,

A client has asked me about the portrait mobile view, if there is anything we can do. The file listing doesn't look great with the address sidebar.

![image](https://user-images.githubusercontent.com/5093264/91165371-9e5dae80-e724-11ea-9b30-bca6c826d5f2.png)

This kind of frontend stuff isn't my best, but if I get pointed the right way don't mind having a crack at some point. In the meantime they are work around with landscape view.

**Comment by keshrath** [comment]
Current Version of MuK DMS and MuK Theme

![image](https://user-images.githubusercontent.com/4851083/91165779-90cb0900-e6d1-11ea-9e7a-7245a2b57855.png)

**Comment by etobella** [comment]
on 12.0 or 13.0? I mean, the panel is from odoo on 13.0, so it is interesting to know if it works properly there :thinking:

**Comment by gdgellatly** [comment]
Sorry that is v13, actually I have an enterprise documents I can check on 12.0.

On 12.0 the panel doesn't show in (Enterprise App) Documents on mobile. As it happens that is what this client wants.

**Comment by etobella** [comment]
The problem with the sidebar cannot be solved without removing it. I mean, this is from Odoo core, so I don't know if much changes can be done there :disappointed: 
However, we are working on a new view that could probably solve this issue :wink:. We made the PR on 12.0, but it will be ported to 13.0
