### ISSUE TITLE
install on odoo CE 14

### ISSUE THREAD

**Issue by frankofno** [OCA/dms#119]
i tried to install dms on a fresh odoo CE 14 edition. 
in order to install dms i need to install web_drop_target. to install web_drop_target i need to install "document" which is no longer available?!

[https://github.com/OCA/web/issues/1973]

how can i get dms up and running on odoo 14 CE?

**Comment by pedrobaeza** [comment]
There's no such dependency:

https://github.com/OCA/web/blob/14.0/web_drop_target/__manifest__.py#L11

**Comment by frankofno** [comment]
just managed to install dms after reinstalling odoo 14 again.. one step closer. dms appears to be installed, although when i click on the Documents menu item i get:

`Traceback:
_createFilterTree@http://192.168.2.11:8069/web/content/363-e1c6e26/web.assets_backend.js:2031:8
_fetchFilters/<@http://192.168.2.11:8069/web/content/363-e1c6e26/web.assets_backend.js:2042:581`
