### ISSUE TITLE
permission rights

### ISSUE THREAD

**Issue by frankofno** [OCA/dms#120]
Hello,

all new to dms v14 on odoo CE 14, first install now finally works and shows up, allthough I can't create folders and uploads docs

`Due to security restrictions, you are not allowed to create 'Directory' (dms.directory) records.

Records: messmedia (id=8)
User: Administrator (id=2)

This restriction is due to the following rules:
- Apply computed create permissions.

Contact your administrator to request access if necessary.`

**Comment by pedrobaeza** [comment]
This issue tracker is not a beginner's guide. It's for real issues. For other things, go to forums. The last tip: see #114
