### ISSUE TITLE
number of files in not showing up in root directory

### ISSUE THREAD

**Issue by frankofno** [OCA/dms#123]
the number of files is showing 0 (zero) although there are 2 files in a subdirectory. 

| folder 1 (o files
|- subfolder 1 (no files)
|-- subsubfolder (with 2 files)
|---file 1
|---file 2

to be honest, that could lead to the assumption sooner or later, the directory is empty so i can delete it. if a subfolder contains a file, that number should appear in the root folder as well.

![Screenshot 2021-07-22 at 00 09 47](https://user-images.githubusercontent.com/35775329/126566959-87298029-2871-46bc-8250-6d98b73c2e81.png)

![Screenshot 2021-07-22 at 00 15 28](https://user-images.githubusercontent.com/35775329/126567048-f69750f1-ffe4-458b-8e59-f0016113d444.png)

**Comment by victoralmau** [comment]
Hello,

With this change https://github.com/OCA/dms/pull/147 will now show the total of files in all subdirectories avoiding this confusing information.

All the best.

**Comment by victoralmau** [comment]
I think this is already solved and we could close this, right?
