### ISSUE TITLE
uploading a file will overwrite the filename

### ISSUE THREAD

**Issue by frankofno** [OCA/dms#124]
since the upload of a file will overwrite or set the name, it should either be the first step instead of asking for name, or it should respect the name already typed in.

typing in a name, than uploading the file, the name previous name is overwritten by the filename. should only happen if the name field is empty / null.

**Comment by victoralmau** [comment]
Hello,

This behavior is general to Odoo (it happens for example when trying to create attachments manually from the form view) and in my opinion it is correct because otherwise inconsistent data could be produced; for example, define the name **test.txt** and upload a file **example.zip**.
