### ISSUE TITLE
extension is needed in filename

### ISSUE THREAD

**Issue by frankofno** [OCA/dms#125]
the field name contains also the extension. If you remove the .pdf for example, the extension is no longer set, the preview thumb is gone and a notification is showing up.

there should be seperate field, where you can set or edit the real filename with extension. the name of the record should be whatever the user wants to type in without extension.

https://user-images.githubusercontent.com/35775329/126568574-670923e1-34d2-40ef-a874-3b2b4a38d102.mov

**Comment by victoralmau** [comment]
Hello,

It is true that this is strange behavior and the extension should be defined based on the `name`, `mimetype` or the `content` of the file.

This change https://github.com/OCA/dms/pull/146 will fix this.

**Comment by victoralmau** [comment]
I think this is already solved and we could close this, right?
