### ISSUE TITLE
Unable to create root directory

### ISSUE THREAD

**Issue by majenkotech** [OCA/dms#134]
I have just freshly installed (version 14.0.4.0.0 in Odoo 14). Made the store fine. Then I go to try and create the root folder, and it tells me:

```
Due to security restrictions, you are not allowed to create 'Directory' (dms.directory) records.

Records: root (id=5)
User: Matt Jenkins (id=2)

This restriction is due to the following rules:
- Apply computed create permissions.

Contact your administrator to request access if necessary.
```

I checked my permissions and I have "dms_directory_base_user" and "dms_directory_user". I even tried restarting odoo to ensure all permissions were flushed and known about by the system.

**Comment by pedrobaeza** [comment]
You have to put the permissions on the created folder.

Closing as no issue, but misuse of the module.

**Comment by majenkotech** [comment]
What do you mean I have to put the permissions on the created folder? Where? What option? Am I missing something?

**Comment by pedrobaeza** [comment]
Each folder has a permission configuration.

**Comment by majenkotech** [comment]
I don't see one. Where should I be looking? I can't create even the first root folder, and there's no permissions in the create directory panel.

**Comment by majenkotech** [comment]
Ah, I think I found it. You have to first create an access group, then add that access group to the directory when you make it. Not obvious, and missing from the instructions.

**Comment by pedrobaeza** [comment]
![Selección_015](https://user-images.githubusercontent.com/7165771/133131323-631f6f76-c332-4d95-bcf7-ff09fc732be8.png)

You can make a pull request for improving the documentation.

**Comment by majenkotech** [comment]
PR #135 created to improve the instructions

**Comment by edisuc** [comment]
If I create a storage of type "Filestore" or "Database", the Groups tab disappears. Also if I change the form to show this tab and add the admin group, the error is still present. What am I missing?

**Comment by alrashiedi** [comment]
I have installed it with odoo 17.0 and created access group and Filestore but still getting the same error while creating the first root directory 
![Screenshot 2024-09-14 195257](https://github.com/user-attachments/assets/b26815b9-b3a4-48ec-8eeb-96e8bbf042a7)
![Screenshot 2024-09-14 195239](https://github.com/user-attachments/assets/9ef2ee52-5d18-48a4-b937-9b84d807167e)

I am using the admin user which already granted Manage permission to documents app.

any help! what I am missing here?

**Comment by alrashiedi** [comment]
I have removed the app and install again and works fine
Thanks
