### ISSUE TITLE
Document preview error

### ISSUE THREAD

**Issue by kimasplund** [OCA/dms#139]
Clicking the magnifying glass just gives missing pdf.

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem in OCA runbot?

**Comment by kimasplund** [comment]
This i honestly dont know.. i just installed and configured it on odoo 14c.Or is there some requierments missing in docs?Sent from my Galaxy
-------- Original message --------From: "Pedro M. Baeza" ***@***.***> Date: 11/10/2021  12:21  (GMT+03:00) To: OCA/dms ***@***.***> Cc: Kim ***@***.***>, Author ***@***.***> Subject: Re: [OCA/dms] Document preview error (#139) 
Steps to reproduce the problem in OCA runbot?

**Comment by pedrobaeza** [comment]
Well, I'm afraid that if you don't reproduce on standard runbot, it's something on your end. There isn't extra requirements for previewing things.

Closing meanwhile no extra steps to reproduce are provided.
