### ISSUE TITLE
Preview for audio files

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/dms#15]
I'm missing a preview for audio files (WAV, MP3, OGG...), which browsers supports natively, but not when trying to preview files from these extensions in DMS. I think this can be a general issue in Odoo preview panel, but not sure right now.

**Comment by etobella** [comment]
Audio files are not supported by Odoo :disappointed:
But, it is not hard to add them, I made a small module showing how (https://github.com/tegin/web/tree/12.0-audio/web_audio_file). We can do two things:
- Create a new module and dms inherit from it
- Make the changes directly to DMS

**Comment by pedrobaeza** [comment]
I think the way to go is:

- Create a module in OCA/social for having that preview in chatter (`mail_audio_preview` or similar).
- Do that the DMS automatically inherit these "extensions" for previewing things without glue modules (I'm not only thinking on audio files, but CAD files, etc).
- Recommend in the DMS README the installation of the module for having preview of other things (we can do a list).

**Comment by etobella** [comment]
Good for me!! I will make the PR of the mail_audio_preview today or tomorrow :wink: 
I will keep this issue until the PR of the first file is created :wink:
