### ISSUE TITLE
Is there a REST-API to upload/download files?

### ISSUE THREAD

**Issue by ghost** [OCA/dms#150]
**Is your feature request related to a problem?**
Is there a REST-API to upload/download files? I couldn't find a documentation for a REST-API to up- and download files.

If there is no REST-API integrated yet, is someone willing to do this for money?

**Comment by pedrobaeza** [comment]
No, the API is XML-RPC/JSON-RPC. https://www.odoo.com/documentation/14.0/developer/misc/api/odoo.html
