### ISSUE TITLE
Error during module uninstallation

### ISSUE THREAD

**Issue by hassanShabbir12** [OCA/dms#152]
## Module
DMS

## Describe the bug
When I tried to Uninstall the module, the logs showed the error about the dms.directory and dms.file models. Now when I am trying to reinstall, it says:
`ERROR dev_dms odoo.schema: Table 'dms_directory': unable to set NOT NULL on column 'name' `
and
`ERROR dev_dms odoo.schema: Table 'dms_file': unable to set NOT NULL on column 'directory_id'`
Would you mind responding to me with the cause and its solution?

**Comment by pedrobaeza** [comment]
I'm afraid that doesn't have anything to do with the module itself or a bug in it, but the way you have done things. Please use forums for asking for help. Anyways, the logs you present are not blocking.
