### ISSUE TITLE
File "C:\Program Files\odoo\server\odoo\addons\base\models\ir_model.py", line 1908, in xmlid_lookup     raise ValueError('External ID not found in the system: %s' % xmlid) ValueError: External ID not found in the system: dms.model_dms_file

### ISSUE THREAD

**Issue by abdelkader-k** [OCA/dms#153]
## Module
The name of the module that has a bug.

## To Reproduce
**Affected versions**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
You are not deploying correctly the module (and Windows is a bad OS target for Odoo, but that's another thing).

Closing as the module doesn't have this problem.
