### ISSUE TITLE
Translate module into Spanish

### ISSUE THREAD

**Issue by androettop** [OCA/dms#16]
Hello, I want to translate the dms module to Spanish. I'm entering https://translation.odoo-community.org/projects/dms-13-0/ but do not have permission to add a new language, how should I proceed?

Regards

**Comment by pedrobaeza** [comment]
Please follow instructions in:

https://odoo-community.org/page/translate

(basically, send a request for being able to translate). Please indicate if you Spanish from Spain or from other Spanish speaking country.
