### ISSUE TITLE
Attachment Preview Error

### ISSUE THREAD

**Issue by man4tech** [OCA/dms#163]
module: dms
version: 13.0

**Steps to reproduce**
Upload a file pdf on a Root or subfolder, try to preview that attachment from document windows or from a record "dms_directory_ids"
Tried without dms_field installed and its same behavior
![screen](https://user-images.githubusercontent.com/44093282/155386400-993a7874-59c7-4ece-b3ce-086f6bb3cc3d.png)

**Current behavior**
When clic on preview buttons the window space is showed, however its show an red "Missing PDF file" and pdf isnt rendered

**Expected behavior**
Display the attachment preview

**Comment by victoralmau** [comment]
I have reviewed the operation of uploading a .pdf and previewing it in runbot 13 and it works correctly:
![runbot-13](https://user-images.githubusercontent.com/4117568/155506986-942242c0-14dd-4dfe-909e-c4bd451722f2.gif)

Perhaps you should check that the code is up to date and that the size of the attached file is allowed in Odoo according to the configuration.

**Comment by man4tech** [comment]
Hi, @victoralmau sorry what version are you using in the demo for dms and dms_field, the drag and drop feature don't work for me either, its showing an error  "Error: url is undefined"

Thanks in advance

**Comment by man4tech** [comment]
> I have reviewed the operation of uploading a .pdf and previewing it in runbot 13 and it works correctly: ![runbot-13](https://user-images.githubusercontent.com/4117568/155506986-942242c0-14dd-4dfe-909e-c4bd451722f2.gif)
> 
> Perhaps you should check that the code is up to date and that the size of the attached file is allowed in Odoo according to the configuration.

Hi, @victoralmau sorry what version are you using in the demo for dms and dms_field, the drag and drop feature don't work for me either, its showing an error  "Error: url is undefined", i have cloned from github repo version 13.0.8.3.0, i can see that on runbot the preview is loaded fullscreen, but for me is loaded on a sidebar to the right

Thanks in advance
