### ISSUE TITLE
The DMS module does not show the preview and differs a lot from the instance that exists in runbot de993f5f 

### ISSUE THREAD

**Issue by man4tech** [OCA/dms#164]
## Module
The name of the module that has a bug.
dms 13.0.8.3.0

## Describe the bug
I have cloned dms commit de993f5f from the source on githuub, however I cannot see the preview of the attachments and I notice several differences (attached screenshots) with respect to what is shown in runbot, for example the preview window in runbot opens in the center in full screen, while in my instance it opens as a side iframe, and neither images nor pdfs are displayed, also drag and drop shows an error.

## To Reproduce
**Affected versions**:
dms 13.0.8.3.0

1. Upload a image o pdf on folder/subfolder
2. Try to preview
3.

**Expected behavior**
When clicking on the pdf or attachment, it should show a centered window with the preview of it, just as it does in runbot without problems 

**Additional context**
Runbot, click on attachment to preview it
![runbot](https://user-images.githubusercontent.com/44093282/155582103-478099a3-196f-48ed-aee0-0ea9fd6d2d68.png)
My instance, click on attachment to preview it
![my instance](https://user-images.githubusercontent.com/44093282/155582107-653660a1-02c6-4f70-85cf-18fea1f2acda.png)
Error doing drag n drop on folder
![dragndrop_error](https://user-images.githubusercontent.com/44093282/155582110-16c623db-e143-489a-9a50-9cf8e6583b8b.png)

Am I doing something wrong by getting the code from github? the command i use is git clone https://github.com/OCA/dms.git --branch 13.0

**Comment by pedrobaeza** [comment]
It's the same code, so there's something incorrect in your deployment, not on the DMS code. Maybe libraries like magic, but this is out of scope of this issue tracker. Please don't open more issues about this and go to forums for further help.
