### ISSUE TITLE
[Q&A] dms_field: change license from AGPL to LGPL

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/dms#169]
@etobella

As the DMS module is LGPL, is there a possibility that the dms_field module can be changed to LGPL as well?

cc @jarroyomorales

**Comment by etobella** [comment]
No problem from my side, can you make the pr? Or can you wait a few days?

@olgamarcocb

**Comment by marcelsavegnago** [comment]
> No problem from my side, can you make the pr? Or can you wait a few days?
> 
> @olgamarcocb

I do. Thanks
