### ISSUE TITLE
DMS  Error

### ISSUE THREAD

**Issue by moh-Rahman** [OCA/dms#173]
## Module
DMS
## Describe the bug
When I started DMS on odoo14 unbunt 20.04
I face this error 

Traceback:
TypeError: this._update_overlay is not a function
    at http:// /web/content/393-e8adef6/web.assets_backend.js:8780:528
    at async Class.start (http:// /web/content/393-e8adef6/web.assets_backend.js:1342:29)
    at async Class.start (http/web/content/393-e8adef6/web.assets_backend.js:1640:1303)

## To Reproduce
**Odoo14**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
You should reproduce the problem on runbot/runboat (clicking on the button on the README). If not, you should probably have incompatible things in your instance.

**Comment by moh-Rahman** [comment]
that right i have something missing but i did not know . If you video to installation or you if you guide me i will  appreciate

**Comment by pedrobaeza** [comment]
Sorry, that's out of the scope of this issue tracker. The module installs the same way as the rest.
