### ISSUE TITLE
dms cannot uninstall

### ISSUE THREAD

**Issue by Bonainifo** [OCA/dms#186]
## Describe the bug
Uninstall module will get an error message
result[data['res_id']].append('%(module)s.%(name)s' % data)

#t about the problem here. (e.g. OS, Python version, ...)

**Comment by victoralmau** [comment]
Hi,

Can you indicate a list of steps to reproduce it in runboat please? Another option could be to add a video here explaining the error and how to get it. 

What version are you using?

A greeting.

**Comment by victoralmau** [comment]
Maybe it is related to https://github.com/OCA/dms/issues/189?
