### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mileo** [OCA/dms#2]
Hi, 

I would like to help with the migration. Do we have any plans for this?

Could I migrate the module https://github.com/muk-it/muk_dms/tree/12.0/muk_dms_attachment ?

Thanks in advance

**Comment by pedrobaeza** [comment]
In fact I would consider this as a must in core module. I think there's not too much sense in embedding the file contents in DB, but putting it as `attachment=True`, and no need to add all of these burden, having automatically the benefits of attachments:

- No duplicated content
- No DB size increase

What do you think, @etobella @keshrath ?

**Comment by etobella** [comment]
Well, Right now it is contempled on the original `dms` module. When you define the `type` of the `dms.storage` you can choose:
* Database: files are embedded on the database
* Filestore: files are managed as attachments, so I think it is not necessary to continue on this.

However, I think it would be interesting to check the version system in order to proceed that way

**Comment by pedrobaeza** [comment]
I was thinking that filestore was for importing an existing server path and parse its contents... but if it's already attachments, I think the other type (database), it's not interesting to be kept.

**Comment by mileo** [comment]
> MuK Documents is a module to create, manage and view files directly within Odoo. MuK Documents Attachment allows to store Odoo Attachments inside the Document Management System. Attachments stored in the document management system are still available as attachments in Odoo. As with all other files, the storage type can be set via the setttings.

I believe that we can have a configuration where the user specifies which models he wants his attachments to become documents in the DMS module.

In addition, the possibility to classify them with tags in a simple way.

Document data in DMS should be easy to search, for example by model (model_id and rec_name).

With the document data well structured we can for example create customizations:

a - Documents attached to the product category, tagged with MRP;
b - Documents attached to the product, tagged with MRP;
c - Documents attached to the Bill of Material, tagged with MRP;

1. Attachments for items a, b, c are automatically displayed in a production order;
2. If you search in DMS by a production order you get the same a,b,c documents;

**Comment by pedrobaeza** [comment]
OK, if the idea is that any attachment in the system in a configurable way - not by default -, becomes a DMS document, I support that idea. Is that what `muk_dms_attachment` does? If so, go ahead with `dms_attachment`!

**Comment by keshrath** [comment]
MuK DMS Attachment uses the DMS to store Odoo Attachments. The basic idea behind that is that you can have all the Odoo Attachment in a structured way.

**Comment by pedrobaeza** [comment]
I would prefer some kind of synchronization between `ir.attachment` and `dms.document` if possible instead of a "replacement". Why? For avoiding glue modules with other modules that modifies one of the involved models.

**Comment by keshrath** [comment]
Yes that might be true. Currently the module adds a store option `documents` like `filestore` or `database` for attachments.
