### ISSUE TITLE
[14.0] DMS : drag field many2one will got error

### ISSUE THREAD

**Issue by Saran440** [OCA/dms#211]
## Module

DMS

## Describe the bug
Before install module DMS, I can drag field many2one is not error
![Before](https://user-images.githubusercontent.com/20896369/191431746-77961988-713b-471c-b811-35929e1e8d20.gif)

After install module DMS, it will error when I drag field many2one
![After](https://user-images.githubusercontent.com/20896369/191431898-310b8cb4-f3e0-47b3-8ee8-9562a9566198.gif)

**Comment by pedrobaeza** [comment]
Dragging this shouldn't be allowed. Isn't this something more of the base module `web_drop_target`?

**Comment by Saran440** [comment]
okay, i move this issue to https://github.com/OCA/web/issues/2298
Thank you :)
