### ISSUE TITLE
Add methods to create folders and files

### ISSUE THREAD

**Issue by Tardo** [OCA/dms#223]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Add "helpers" to create folders and files using "os path" syntax. like 'my_file/is/here.pdf'

**Describe alternatives you've considered**
Do it manually

**Additional context**
I think that can be useful have methods to create folders and files easy.

Examples:
- `self.env['dms.directory'].create_dir('this is/my/custom/folder', root_dir=self.env.ref('foo.custom_root_dir'))`
** If 'root_dir' is defined, 'this is' is a subfolder... if not... is a root folder.

- `self.env['dmd.file'].create_file('this is/my/custom/folder/the-file.pdf', content=base64.b64encode(...), root_dir=self.env.ref('foo.custom_root_dir'))`
** This method uses 'create_dir' and do the create operation for 'dms.file'.

Do you think it can be useful?

**Comment by pedrobaeza** [comment]
The virtual hierarchy in the DMS shouldn't have any direct relation with the physical one, so I don't think the DMS should have directly that.

**Comment by Tardo** [comment]
Thanks for the quick response!

My intention was mostly to give an easy way to create folder hierarchies. Maybe something could be done in another way without using strings (paths)?

For example, in my use case I always generate the file using the same hierarchy (varies per client and some other parameter). So, I follow a pattern but not static enough to be able to write it in a "data/record.xml".

So, it is easy for me to work by having a method that builds me the folder hierarchy... it creates them or gives me the record if it already exists.

**Comment by pedrobaeza** [comment]
As said, the directories in the DMS doesn't correspond with real folders in the physical store. It depends on the chosen store. You have to split concepts.

**Comment by Tardo** [comment]
I am aware that it has nothing to do with physical storage. But you still have folder hierarchy. Otherwise... what is the point of having non-root folders?

Thank you for your time.

**Comment by pedrobaeza** [comment]
It's a logical structure for managing your information, but all inside Odoo.
