### ISSUE TITLE
DMS tab is missing

### ISSUE THREAD

**Issue by Puhlik77** [OCA/dms#247]
## Module
DMS

Installed on a CE v.14. Installed all extra modules as required ("DMS", "web_drop_target", "mail_preview_base", "dms_field" "dms_action). Configured as prescribed in instructions. Still missing the tab in contact module.

**Comment by Home-Based** [comment]
The problem seems to be more general than suspected (see #189).

I still can't attach documents to a specific partner without the DMS tab in the contact module. 

I could create a storage (attachement type), link it to res.partner model, create a root directory, but no possibility to link a subfolder to a record.

I'm still ready to help to solve this issue, but I have no idea where to search. 

Best reagards,

SA

**Comment by iBuilderBY** [comment]
I found this: if the DMS is installed on a standard database with ODOO demo data, then everything works - tabs are shows. If I install to a new database, it is not displayed.

**Comment by Home-Based** [comment]
Our database was a new one, indeed.

**Comment by pedrobaeza** [comment]
The module is not adding anything on partner model. You have to add it coding.

Closing as no real issue, but misuse.

**Comment by pedrobaeza** [comment]
Anyway, on demo data of the module, you can see the effect on the partner form:

![Selección_010](https://github.com/OCA/dms/assets/7165771/cc8ce6c0-828c-40b7-afd1-fec4fd9ed1a4)

Check https://github.com/OCA/dms/blob/15.0/dms_field/demo/partner_dms.xml

**Comment by Home-Based** [comment]
It is exactly what is MISSING on our Odoo environments !

So can you elaborate on our MISUSE ?? What did you CODE to obtain this DMS tab ? Because this info doesn't appear anywhere...

Thanks.

SA

**Comment by pedrobaeza** [comment]
Check the demo data, and you have to add that code.

**Comment by Puhlik77** [comment]
I have that partner_dms.xml already in our CE 14, but still no dms tab.


    On Tuesday, August 22, 2023 at 05:48:21 a.m. EDT, Pedro M. Baeza ***@***.***> wrote:  
 
 


Check the demo data, and you have to add that code.

**Comment by Puhlik77** [comment]
I have that partner_dms.xml already in our CE 14, but still no dms tab. Need it in a production enviroment
![image](https://github.com/OCA/dms/assets/85707137/0a7e9d57-d137-42e9-9384-fc6db3139e5a)

**Comment by pedrobaeza** [comment]
They are demo data, and your DB doesn't have demo data. That's why I'm saying you need to code yourself into a module that.

**Comment by iBuilderBY** [comment]
I found what I can do, I will write in detail later when I will check everything.

**Comment by Home-Based** [comment]
> I found what I can do, I will write in detail later when I will check everything.

Hi iBuilderBY, 

Any solution found ? If yes, could you indicate us how to proceed ? 

Many thanks,

SA

**Comment by iBuilderBY** [comment]
> > I found what I can do, I will write in detail later when I will check everything.
> 
> Hi iBuilderBY,
> 
> Any solution found ? If yes, could you indicate us how to proceed ?
> 
> Many thanks,
> 
> SA

Sorry, I haven't time to check all issyes. I'll chcek all late. the main idea is to manually make an xlm where it is specified where the list of files should be shown, it does not appear itself. I did this in one place - everything appeared, but I didn't check in other places. See example https://github.com/OCA/dms/blob/15.0/dms_field/demo/partner_dms.xml
If you don't figure it out, let me know, I'll write as soon as I can check.

**Comment by Home-Based** [comment]
@iBuilderBY Many thanks for those comments.

I suppose I have to create a new view and insert the content of the xml under architecture. But...  

View type : Form ? 
Model : res.partner ?
Inherit view : res.partner.form ?
Inherit view mode : basic ?

Any modifications to bring to the xml content ?

Many thanks for help.

SA
