### ISSUE TITLE
i cant create an attachment storage type file, the field "res_id" is readonly, so raise "A file must have model and resource ID in attachment storage."

### ISSUE THREAD

**Issue by wubxi** [OCA/dms#251]
## Module
The name of the module that has a bug.

## To Reproduce
**Affected versions**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
For attachment storage, you should do things from the source part, attaching files, not on the DMS, that is a "dump" of them. Choose another storage type.

**Comment by wubxi** [comment]
Must it be used together with the 'dms_field' module to create attachment type storage?

**Comment by pedrobaeza** [comment]
No, I have already explained what you have to do with attachment storage.

**Comment by wubxi** [comment]
thanks
