### ISSUE TITLE
error message: This file could not be decoded as an image file.

### ISSUE THREAD

**Issue by ccandito** [OCA/dms#255]
Hi, 
in uploading a pdf file the following error has occurred:
This file could not be decoded as an image file.

Regards
Claudio Candito

**Comment by pedrobaeza** [comment]
Please reproduce the problem in runboat and put the steps to reproduce and the image. Make sure you have latest code, and include the Odoo version.

**Comment by ccandito** [comment]
Odoo version 15
I've created a file and tried to change it by assigning another file.
Regards
Claudio Candito

**Comment by ccandito** [comment]
the image of the error
Thanks in advance
[error.docx](https://github.com/OCA/dms/files/12072937/error.docx)

**Comment by pedrobaeza** [comment]
@victoralmau it seems c0179b2e630db7d37504091f3487803455932004 is also needed on v14/v15

**Comment by ccandito** [comment]
By applying the above correction the issue is solved
Regards
Claudio Candito

**Comment by pedrobaeza** [comment]
Applying them on PRs now

**Comment by ccandito** [comment]
Before implementing it, it is necessary to change the correction as follows:

if one.mimetype != "application/pdf" and one.res_mimetype in
(*Image.MIME.values(), "image/svg+xml"):


regards

Claudio

Il giorno mar 18 lug 2023 alle ore 10:22 Pedro M. Baeza <
***@***.***> ha scritto:

**Comment by victoralmau** [comment]
Fixed already in 15.0 with https://github.com/OCA/dms/pull/258
