### ISSUE TITLE
[Question] why content field is compulsory

### ISSUE THREAD

**Issue by ygol** [OCA/dms#27]
Is it on purpose to require the "content" field to be populated when creating a document?

If it wasn't we could create a "placeholder" document before actually receiving it. 
Same as "request document" in enterprise's document application.

thanks

**Comment by pedrobaeza** [comment]
Well, I'm not sure if that will lead to any problem. Have you tried locally to remove that requirement? @keshrath @etobella do you predict any problem with that?

**Comment by etobella** [comment]
Probably that could give problems with mimetype and icon, but that can be fixed
