### ISSUE TITLE
permision denied

### ISSUE THREAD

**Issue by MarcosGraficon** [OCA/dms#299]
I just downloaded the app and gave me all the permissions by adding me to the admin grupo of dms, then i created the storesistem and fine, but when i try to create a folder it thorws me an excepcion of perms that i dont have it, but i have the dms.directory ODOO15
![image](https://github.com/OCA/dms/assets/156304478/09402d8c-90eb-4c65-b64b-7b79550f269e)

**Comment by victoralmau** [comment]
Hello, 

Have you set any access group (with any permissions and minimum your user) in the directory you are creating? 
This is explained in the CONFIGURATION section of the readme of the `dms` module.

Best regards.
