### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by etobella** [OCA/dms#3]
After the merge of #1, it is interesting to talk about versions. Original @Muk-it had a custom module but I think it is on their private repos. I am interested on migrating/create this set of modules and any starting work is welcome. :smile: 

@keshrath @pedrobaeza

**Comment by pedrobaeza** [comment]
Yeah, it's the logical roadmap.

**Comment by keshrath** [comment]
I was on holiday the last week and have to get up to speed with my projects, but I will open a PR for this as soon as I have a bit of free time.

**Comment by keshrath** [comment]
PR: https://github.com/OCA/dms/pull/28
