### ISSUE TITLE
Can't hide attachment type directory(ies) from portal user.

### ISSUE THREAD

**Issue by peterromao** [OCA/dms#304]
Which is the same as saying that one should be able to restrict the access to the directories in the portal view for the attachments directories to internal users.

I can see nowhere to be able to do this.

One can hide this type of storage from appearing but then it is hidden for the internal users too.

Any ideas?

P.S. This is neither a bug report nor a feature request. It's more of a design intent issue.

Thanks,

**Comment by victoralmau** [comment]
Hi,

The attachment storage type causes the permissions to be those of the linked record. If a user accessing the portal can access a record, they will be able to access the files in the linked directory. This behavior is specially what is expected with that type of storage.

If you wish, you can add a PR with the improvement you consider.

Best regards.
