### ISSUE TITLE
Support attachment categorization / tags?

### ISSUE THREAD

**Issue by Rad0van** [OCA/dms#31]
I would like to be able to categorize and/or tag attachments (primarily on products but more general approach is fine). The reason is there are many kinds of documents for products we sell like user manuals, technical manuals, schemas, guarantee certificates, other certificates... We'd need a flexible way to group/filter these to be able to quickly find what is needed. I'd also use it for filtering documents that should be displayed on website - some in shop, some in customer portal, ...

Currently reviewed PR #9 integrates ir.attachments into DMS which provides both categories and tags. However looking at the code the integration goes in opposite direction - DMS document points to ir.attachment not the opposite way around. The ideal outcome would be changed view on attachments, where one would at least see (edit optionally - but that could be done in DMS as it is currently) category and tags. So these would be available as attributes of the ir.attachment so they could be used elsewhere as well.

Is this feasible or stupid idea?

**Comment by etobella** [comment]
Filtering there obviously needs to modify the widget in order to allow filters.

Another option would be to allow filtering of tags and so-on on #12

**Comment by pedrobaeza** [comment]
First of all, if you decide to go to the attachment part, this should go to OCA/knowledge, not here. Second, I think you should improve the bidirectional way of the attachment integration instead of handling the attachment part that is harder.

**Comment by Rad0van** [comment]
> Filtering there obviously needs to modify the widget in order to allow filters.
> 
> Another option would be to allow filtering of tags and so-on on #12

Will have a look at that but it seems highly interesting.

**Comment by Rad0van** [comment]
> First of all, if you decide to go to the attachment part, this should go to OCA/knowledge, not here. Second, I think you should improve the bidirectional way of the attachment integration instead of handling the attachment part that is harder.

You mean to expose DMS attributes like category and tags as attributes of linked attachment? That would certainly be the first step.

**Comment by pedrobaeza** [comment]
Well, I think all that work should go on DMS, and you only need to add a link from each product to DMS to show "related documents".

**Comment by Rad0van** [comment]
> Well, I think all that work should go on DMS, and you only need to add a link from each product to DMS to show "related documents".

Well I thought more in a way like to add many2one relation from ir.attachment to dms.file and thus in fact forming 1:1 relation and through that publish related category_id and tag_ids on ir.attachment. That way I could create a list view for attchmanets where I could filter, ... This would also work for attachments attached to any kind of object I guess.

**Comment by pedrobaeza** [comment]
But why listing attachments? List documents...

**Comment by Rad0van** [comment]
> But why listing attachments? List documents...

Well you're probably right. I view from the point of view of current users who only know attachments now as a way to have some files related to objects. But I guess if DMS was used (esp. with #12 ) we could change their behavior to look at documents instead. Is that what you have in mind?

**Comment by pedrobaeza** [comment]
Only with #24 and a link from chatter to related documents is enough IMO.

**Comment by Rad0van** [comment]
> Only with #24 and a link from chatter to related documents is enough IMO.

I'll add that to my queue of things to investigate and possibly work on. It's getting longer and longer. Thanx for hints.
