### ISSUE TITLE
DMS 16 restriction error

### ISSUE THREAD

**Issue by himanshuhippo** [OCA/dms#341]
## Module
Document Management System 16 

## Describe the bug
1. Logged in as Administrator with all default permissions/access and with document>manager access. 
2. While making a Directory in DMS i am getting this error . 
//Access Error
Due to security restrictions, you are not allowed to create 'Directory' (dms.directory) records.
Records: Documents Main (id=10)
User: Administrator (id=2)

This restriction is due to the following rules:
- Apply computed create permissions. //

**Comment by pedrobaeza** [comment]
You have to add yourself in a group in the directory. It doesn't matter to be admin or DMS admin. DMS requires explicit permissions on the directories.

Closing as no issue.
