### ISSUE TITLE
error when one click the icon in dms_file

### ISSUE THREAD

**Issue by hitrosol** [OCA/dms#347]
## Module
The name of the module that has a bug.
dms_file

## Describe the bug
Error shown when the one click the icon in dms_file

## To Reproduce
**Affected versions**:
V16.
It works well in v14 and v15

1. Click menu Documents --> Documents
2. Click any Directory
3. The icons toolbar shown
<img width="247" alt="Screen Shot 2024-06-20 at 10 34 45" src="https://github.com/OCA/dms/assets/5949936/d4424c82-91c0-41d7-a5b8-47e2986e1e0f">

4. Click the button "Create directory" or "Create File" or "Open"
5. The error shown as follows:
<img width="973" alt="Screen Shot 2024-06-20 at 10 38 11" src="https://github.com/OCA/dms/assets/5949936/eb600f6a-9ace-4e7e-8216-62bd62f93960">

6. The same error is also shown if one select the file and click the Open Icon.

**Expected behavior**
The regular new form is shown whenever one click the icon.

Thanks

**Comment by pedrobaeza** [comment]
I think you mean `dms_field`

**Comment by CarlosRoca13** [comment]
Hmmm, I'm not having the error...

Tes on runboat:
![dms_field_no_error](https://github.com/OCA/dms/assets/35952655/b35c7b9b-fe5d-427c-b4bd-e447b97a6b33)

**Comment by CarlosRoca13** [comment]
I found the error, I will solve it. Thank you for the review

**Comment by hitrosol** [comment]
resolved
