### ISSUE TITLE
Preview panel icon

### ISSUE THREAD

**Issue by yowilfre82** [OCA/dms#351]
## Module.
I think is in dms_field

## Describe the bug
When click on a tree node , the icon don't show in the Preview Panel 

![image](https://github.com/user-attachments/assets/f162e321-f974-4a5c-9b1a-7e3b8353f2aa)

## To Reproduce
**Affected versions**:
14

**Expected behavior**
![image](https://github.com/user-attachments/assets/e4502747-3bd0-4dec-beec-2f55de309c85)

**Comment by yowilfre82** [comment]
Please my  problem is in dms_field v14 not 16

**Comment by pedrobaeza** [comment]
Well, you should backport the proposed fix.

**Comment by yowilfre82** [comment]
> Well, you should backport the proposed fix.

I'm sorry, but what do you mean? I don't understand.

**Comment by pedrobaeza** [comment]
We are doing the fix for 16.0. There's no guarantee that we provide the fix also for 14.0.

**Comment by yowilfre82** [comment]
> We are doing the fix for 16.0. There's no guarantee that we provide the fix also for 14.0.

Sad situation, because i'm using 14.0, where the issue was found. Please, try to do it for 14.0

**Comment by victoralmau** [comment]
Already fixed in v14 with https://github.com/OCA/dms/pull/357
Remember to use more recent versions, many improvements or corrections are only done there.
