### ISSUE TITLE
copy share link by copy icon does not work (link not created at clipboard)

### ISSUE THREAD

**Issue by clxadmin** [OCA/dms#376]
dms version 16

## Describe the bug
copy share link by copy icon does not work (link not created at clipboard)

## To Reproduce
version 16
Testet at runboat: http://oca-dms-16-0-pr375-255a821dce34.runboat.odoo-community.org/

1. open any file at dms
2. try to Action>>Share -- try to copy the link via copy icon
3. no link is at your computers clipboard

**Expected behavior**
the share link is at computers clipboard

**Comment by victoralmau** [comment]
Ping @CarlosRoca13 can you check this?

**Comment by CarlosRoca13** [comment]
Sure

**Comment by CarlosRoca13** [comment]
I think this is something about runboat...

![image](https://github.com/user-attachments/assets/33ea69d9-1911-4fb6-aab8-74f94dcc0ef1)

I have tested it by installing the module locally, and I haven't had any issues.

**Comment by victoralmau** [comment]
It seems to be something related to https, if tested in runboat with https it works correctly, I guess it will be some limitation of the browsers that we did not know, in that case it is not a bug.

**Comment by pedrobaeza** [comment]
Yes, accessing the clipboard is limited to secure connections. It also happens in any part of Odoo. You may want to add that to the ROADMAP.
