### ISSUE TITLE
no conten at contact >> dms tab

### ISSUE THREAD

**Issue by clxadmin** [OCA/dms#377]
No content at contact >> dms tab

## Module
dms version 16

## Describe the bug
if dms modules are installed - no content is visible at contact >> dms tab
see: https://prnt.sc/Xe6irbDQe5oR
what is the idea?

## To Reproduce
testet at version 16 runboat http://oca-dms-16-0-pr375-255a821dce34.runboat.odoo-community.org

1. menu contact
2. tab DMS
3. no content see: https://prnt.sc/Xe6irbDQe5oR

**Expected behavior**
what is the idea here ?

**Comment by victoralmau** [comment]
This can be closed, it is already solved https://github.com/OCA/dms/pull/378.
