### ISSUE TITLE
Drag and Drop doesn't work

### ISSUE THREAD

**Issue by Solexplorer** [OCA/dms#39]
Hey everyone,

I installed this module in my local environment and I am experiencing a rather strange issue.
When I try to drag and drop a file, it's asking me for a directory even tho I selected that one in the sidebar. 
How do I tell the system to which directory save the file?
This is what I'm doing:
- Choose the directory from the sidebar
-  Drag the file from my directory
- Drop the file
And I'm getting back the error `You must select a directory first`

![58cf8481-fec5-4c02-b3bf-45bc415abb9e](https://user-images.githubusercontent.com/50027175/100366291-f5fc0680-3000-11eb-9f9a-0cfaf862c7a0.gif)

My question is: is this a bug or there is another way to drag&drop the file?

**Comment by pedrobaeza** [comment]
Odoo version?

**Comment by Solexplorer** [comment]
> Odoo version?

Odoo 12

**Comment by pedrobaeza** [comment]
@etobella is that a legit case to catch the directory from the control panel?

**Comment by pedrobaeza** [comment]
@Solexplorer the control panel is a filter, but it's not determining the folder. I'm not sure if we can take it from there in that specific case.

**Comment by Solexplorer** [comment]
How is the drag and drop supposed to work tho? I can't find a way to make it work

**Comment by pedrobaeza** [comment]
I think it's going to the folder, and seeing the files from that folder, but I haven't yet tried, or maybe it's a bad backport from 13.0

**Comment by Solexplorer** [comment]
I was able to make it work, but tbh it feels like bad UX. IMO a user should be able to upload the file from the main view and not go to Directories->Directory files->Upload

**Comment by Solexplorer** [comment]
I don't know if it's an expected behaviour tbh at this point

**Comment by kos94ok-3D** [comment]
@Solexplorer 
Is it fixed here: https://github.com/OCA/dms/pull/51 ?

**Comment by pedrobaeza** [comment]
Yes, fixed.
