### ISSUE TITLE
Subdirectories bug

### ISSUE THREAD

**Issue by thopv133802** [OCA/dms#40]
when I try to access subdirectories !
![image](https://user-images.githubusercontent.com/44016234/101469093-dbb61700-3976-11eb-9c9d-8a84ab18726e.png)
![image](https://user-images.githubusercontent.com/44016234/101469130-e83a6f80-3976-11eb-9815-ef6870264088.png)
![image](https://user-images.githubusercontent.com/44016234/101469155-f1c3d780-3976-11eb-9956-61a08d09d5ad.png)
![image](https://user-images.githubusercontent.com/44016234/101469167-f5eff500-3976-11eb-8b8d-5ee91ee9358f.png)
![image](https://user-images.githubusercontent.com/44016234/101469225-0c964c00-3977-11eb-93b8-ec2f52730fa9.png)

**Comment by pedrobaeza** [comment]
Can you explain a bit the problem? Maybe a video? You should also try on runbot, not on local, as maybe your problem is something of the deployment.

**Comment by gaikaz** [comment]
I think what he is trying to show here is that the currently open directory is always shown as a sub-directory of itself, which leads to this "inception" sort of behavior (look at the breadcrumbs of each screenshot). 
I also agree that this is kind of misleading for the end-user as it is very unusual for any kind of "File explorer" programs.

**Comment by victoralmau** [comment]
IMO it's solved with https://github.com/OCA/dms/pull/117 in 13.0, right?

**Comment by yajo** [comment]
Yes, it should. Reopen otherwise please.
