### ISSUE TITLE
[12.0] Current user id overwritten by website user (id=4)

### ISSUE THREAD

**Issue by filipocc** [OCA/dms#42]
Hi there,
i've just installed DMS module and everything works properly at first. But I found something in the code that i cannot understand:
https://github.com/OCA/dms/blob/3a6380e7e93d9365b177c77fa5229f7114777e33/dms/controllers/portal.py#L117
https://github.com/OCA/dms/blob/3a6380e7e93d9365b177c77fa5229f7114777e33/dms/controllers/portal.py#L205

Why current user id (logged user) is overwrite by website user? I mean, whenever I try to access a directory, it throws me an error because user id (4) doesn't have permissions.
As a workaround, the solution is simple:

![image](https://user-images.githubusercontent.com/15066476/103405750-75c54580-4b58-11eb-8f45-203482d9740d.png)

But I would like to know the purpose of that.
Thanks in advance.

**Comment by nabilragab** [comment]
That's bad, check my recently submitted issue.
