### ISSUE TITLE
Storage link to Model

### ISSUE THREAD

**Issue by h3llopy** [OCA/dms#43]
I couldn't find this one to v12 is this available?

![image](https://user-images.githubusercontent.com/63976042/104080467-07246e00-5263-11eb-9875-9cadb1812971.png)

**Comment by pedrobaeza** [comment]
You shouldn't be using latest version.

**Comment by pedrobaeza** [comment]
Or maybe some opened PRs. In any case, this is for notifying issues with the code, not questions.

**Comment by h3llopy** [comment]
thanks @pedrobaeza
