### ISSUE TITLE
Access Groups failure system compromised | URGENT

### ISSUE THREAD

**Issue by nabilragab** [OCA/dms#44]
I have been thoroughly testing out this module for a live use case scenario on an ODOO13 implementation.

What I have come to realize that its possible to gain access to other files in other access groups when the following scenario occurs:

-Create New DB Storage
-Create Root Directory Folder with Admin Only access permission group
-Create Sub Folders with Portal Users example: "Joels Files" "Marcs Files"
-Give Explicit User Access via Group permission to every individual folder. (Hence either user shouldn't be able to access the other files)
-Upload Files to individual directories
-Login to the portal for Marc, Marc will find his files, but in the breadcrumbs, he is able to access the root directory that contains other users folders and gain access to their files.

TESTED:
-Deleted all-access group permissions (with no access groups defined, files and dirs must be completely inaccessible):
DMS still accessible publicly via URLs such as http://localhost:8069/my/dms/directory/20

Something is seriously wrong with the session management and security groups access implementation, unfortunately, I don't have the time to fully investigate this issue.

QUICK EASY TEST:
-Install Demo
-Install DMS
-Log out
-Demo Links are accessible by the public:
http://localhost:8069/my/dms/directory/1
http://localhost:8069/my/dms/directory/11
http://localhost:8069/my/dms/directory/2

**Comment by pedrobaeza** [comment]
DMS has a allow all by default. You should restrict them by groups. See also #41 proposal, but it's not wrong, simply not your choice. Closing thus.
