### ISSUE TITLE
Install for Odoo 14

### ISSUE THREAD

**Issue by Habsah** [OCA/dms#45]
Hello,
I'm a beginner in odoo development,
And I would really appreciate if someone can help me to install this DMS for Odoo (version 14)

**Comment by pedrobaeza** [comment]
It's not ready yet.

**Comment by Habsah** [comment]
Can I ask when is it expected to be ready?

**Comment by pedrobaeza** [comment]
There's no intention expressed by any contributor to migrate them for now. You can ask for a quotation for migrating them by any of the authors/contributors to speed it up.
