### ISSUE TITLE
WARNING popup on dms directory

### ISSUE THREAD

**Issue by francisrubio06** [OCA/dms#50]
I just clone version 13.0 from this repository and install the dms 13.0.3.0.2 module.

But every time I try to create or write a dms.directory record, this warning message keeps opening

dms.directory(<NewId 0x7f53c1230438>,).parent_id

![image](https://user-images.githubusercontent.com/19362305/104952068-c975c280-5991-11eb-853c-318bb1c90800.png)

**Comment by pedrobaeza** [comment]
Is this something reproducible on the runbot instance?

**Comment by francisrubio06** [comment]
@pedrobaeza  How can I check that?

**Comment by pedrobaeza** [comment]
Click on the "Runbot | Try me" button that is on the README.

**Comment by francisrubio06** [comment]
Can't find any buttons in the Readme document

**Comment by pedrobaeza** [comment]
![Selección_011](https://user-images.githubusercontent.com/7165771/104953238-4cb10b80-59c6-11eb-9f86-caaf3b203134.png)

**Comment by francisrubio06** [comment]
No, In the runbot the warning popup does not show

**Comment by pedrobaeza** [comment]
Then there's something wrong on your side. Try updating Odoo code and DMS code.
