### ISSUE TITLE
[13.0] Record Ref selection bug

### ISSUE THREAD

**Issue by ghost** [OCA/dms#60]
With attachment type storage, cannot open files and directories, because record_ref fields have "selection=[ ]".

In local i solved with a function like this:

    @api.model
    def _get_ref_selection(self):
        models = self.env['ir.model'].search([])
        return [(model.model, model.name) for model in models]
        
 Hope is useful

**Comment by pedrobaeza** [comment]
But why do you need `record_ref`? I don't think it's a required field.

**Comment by ghost** [comment]
Is a computed field:

```
    record_ref = fields.Reference(
            string="Record Referenced",
            compute="_compute_record_ref",
            selection=[],
            readonly=True,
            store=False,
        )
```

**Comment by pedrobaeza** [comment]
But why is a problem then?

**Comment by ghost** [comment]
Because, when you open a file or a directory gives an error and you can't open them

**Comment by victoralmau** [comment]
Please, can you describe steps to reproduce in runbot?
I have try to open a directory or file in runbot 13.0 and don't get any problem.

**Comment by ghost** [comment]
Yes, of course:

- Create a storage with "Save Type" = attachment, select a model from Linked Models (e.g res.partner)
- Create a directory from this storage and save it, edit it and set the model field (e.g res.partner)
- Now open a contact and upload a file from the chatter box as attachment
- Go to Documents and try to open that file, or the directory generated

**Comment by victoralmau** [comment]
We can close this now, right?
