### ISSUE TITLE
[13.0] Filestore Data?

### ISSUE THREAD

**Issue by ghost** [OCA/dms#65]
When you create a Filestore Storage, where will be saved the files? I can't find anything about it. Thanks

**Comment by pedrobaeza** [comment]
Filestore is something of Odoo itself, so you should learn how it works. Do a search about it.

**Comment by ghost** [comment]
I know what is odoo filestore. In previous Muk Dms versions, you can choose the path where the files will be saved, here you can't. When you create a Dms Storage selecting Filestore Type, the directories and the files are not created on odoo filestore, so I asked where the files are saved

**Comment by pedrobaeza** [comment]
They are created there, but not isolated. It uses hash technique, storing where it belongs, and not duplicating content if you already have it in other place (like attachment).

**Comment by ghost** [comment]
Ok, so the behavior of previous versions was not preserved anyway :-/
