### ISSUE TITLE
odoo 14 error

### ISSUE THREAD

**Issue by saeed-raeisi** [OCA/dms#77]
odoo-14.0\odoo-14.0\odoo\http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: can only concatenate tuple (not "list") to tuple

**Comment by pedrobaeza** [comment]
Is this happening using the current pull request that migrates the module to 14.0? If so, put the steps to reproduce the problem there. If you're trying to use another version code, then it's logical that it doesn't work.

**Comment by saeed-raeisi** [comment]
There are no modules in the 14-branch

Available only in 13 What should I do to use version 14?

**Comment by pedrobaeza** [comment]
Pull request: https://github.com/OCA/dms/pull/66
