### ISSUE TITLE
Record Rules Bug

### ISSUE THREAD

**Issue by gdgellatly** [OCA/dms#86]
Hi,

I've spent a couple of hours and can't seem to track this down.

Have a setup of say
Root -> Dir A -> Subdir x
         -> Dir B -> Subdir y

So A and B are root directories and they have Security Group A and B with read access respectively as well as an admin group with CRUD. inherit groups is set on subdir x and y.

Security group A and B each contain 1 user - User A, and User B. 
Both users have Documents/User access rights.

Clicking the Documents Tile as one of those users - Record Rule error - read on Directory
Cut and paste a known good link to the files kanban - Record Rule error - read on Directory
Cut and paste a known good link to the directories kanban - works as expected.

**Comment by victoralmau** [comment]
Hi,

Reviewing what you indicate it seems that there is an error following your steps.
I have created a PR (https://github.com/OCA/dms/pull/87) that will solve this problem.

**Comment by victoralmau** [comment]
Now, it's solved in 13.0 and 14.0.
