### ISSUE TITLE
dms file path

### ISSUE THREAD

**Issue by LaxmanKalewar** [OCA/dms#89]
How to get file path when file store type is filestore?
please suggest me.

Thank You

**Comment by pedrobaeza** [comment]
That's something outside DMS. It's a general Odoo thing. The filestore is... where you have configured Odoo to have it. Simply that. And it depends on your deployment.

**Comment by LaxmanKalewar** [comment]
Thank You pedrobaeza for your reply.

**Comment by LaxmanKalewar** [comment]
> That's something outside DMS. It's a general Odoo thing. The filestore is... where you have configured Odoo to have it. Simply that. And it depends on your deployment.

Thank You
