### ISSUE TITLE
upload file problem

### ISSUE THREAD

**Issue by saeed-raeisi** [OCA/dms#90]
hi
When the file size is more than 5 megabytes, the connection to the server is lost and it is unable to upload
![image](https://user-images.githubusercontent.com/38601142/120097781-a4ffd300-c147-11eb-81b5-6b06e76961fd.png)
Connection lost Attempt to reconnect...

**Comment by victoralmau** [comment]
Hi,

I have tried to reproduce in 13.0 for example.
- In local i have successfully upload a 20Mb pdf example.
- In runbot "_Connection lost_" appear with these error:
```
413 Request Entity Too Large 
nginx/1.14.2
```
Have you correctly configured nginx for large file sizes?

**Comment by saeed-raeisi** [comment]
There was no problem exactly on local and the limit is only 25 m
Can you send nginx config?

> Hi,
> 
> I have tried to reproduce in 13.0 for example.
> 
> * In local i have successfully upload a 20Mb pdf example.
> * In runbot "_Connection lost_" appear with these error:
> 
> ```
> 413 Request Entity Too Large 
> nginx/1.14.2
> ```
> 
> Have you correctly configured nginx for large file sizes?

**Comment by pedrobaeza** [comment]
This is a configuration topic, both in Odoo and in reverse proxy, so outside of this issue tracker.
